### ISSUE TITLE
MinGW64 Zest mrbgem.rake error.

### ISSUE THREAD

**Issue by FormulaGX** [zynaddsubfx/zyn-fusion-build#52] opened 2020-05-13 12:33 UTC
Pardon, I'm a bit new to this. Is there something I should look out for?

```
---------Getting Zest---------------------
Cloning into 'mruby-zest-build'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 39 (delta 0), reused 21 (delta 0), pack-reused 0
Receiving objects: 100% (39/39), 52.74 KiB | 8.79 MiB/s, done.
Submodule 'deps/mruby-complex' (https://github.com/pbosetti/mruby-complex) registered for path 'deps/mruby-complex'
Submodule 'deps/mruby-dir' (https://github.com/iij/mruby-dir) registered for path 'deps/mruby-dir'
Submodule 'deps/mruby-dir-glob' (https://github.com/gromnitsky/mruby-dir-glob) registered for path 'deps/mruby-dir-glob'
Submodule 'deps/mruby-errno' (https://github.com/iij/mruby-errno) registered for path 'deps/mruby-errno'
Submodule 'deps/mruby-file-stat' (https://github.com/ksss/mruby-file-stat) registered for path 'deps/mruby-file-stat'
Submodule 'deps/mruby-glew' (https://github.com/IceDragon200/mruby-glew) registered for path 'deps/mruby-glew'
Submodule 'deps/mruby-glfw3' (https://github.com/IceDragon200/mruby-glfw3) registered for path 'deps/mruby-glfw3'
Submodule 'deps/mruby-io' (https://github.com/iij/mruby-io) registered for path 'deps/mruby-io'
Submodule 'deps/mruby-nanovg' (https://github.com/mruby-zest/mruby-nanovg) registered for path 'deps/mruby-nanovg'
Submodule 'deps/mruby-process' (https://github.com/iij/mruby-process) registered for path 'deps/mruby-process'
Submodule 'deps/mruby-regexp-pcre' (https://github.com/iij/mruby-regexp-pcre) registered for path 'deps/mruby-regexp-pcre'
Submodule 'deps/mruby-set' (https://github.com/yui-knk/mruby-set) registered for path 'deps/mruby-set'
Submodule 'deps/mruby-sleep' (https://github.com/matsumoto-r/mruby-sleep) registered for path 'deps/mruby-sleep'
Submodule 'deps/nanovg' (https://github.com/memononen/nanovg) registered for path 'deps/nanovg'
Submodule 'deps/pugl' (https://github.com/mruby-zest/pugl.git) registered for path 'deps/pugl'
Submodule 'deps/rtosc' (https://github.com/fundamental/rtosc) registered for path 'deps/rtosc'
Submodule 'mruby' (https://github.com/mruby/mruby) registered for path 'mruby'
Submodule 'src/mruby-qml-parse' (https://github.com/mruby-zest/mruby-qml-parse) registered for path 'src/mruby-qml-parse'
Submodule 'src/mruby-qml-spawn' (https://github.com/mruby-zest/mruby-qml-spawn) registered for path 'src/mruby-qml-spawn'
Submodule 'src/mruby-zest' (https://github.com/mruby-zest/mruby-zest) registered for path 'src/mruby-zest'
Submodule 'deps/osc-bridge' (https://github.com/mruby-zest/osc-bridge) registered for path 'src/osc-bridge'
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-complex'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-dir'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-dir-glob'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-errno'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-file-stat'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-glew'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-glfw3'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-io'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-nanovg'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-process'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-regexp-pcre'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-set'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/mruby-sleep'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/nanovg'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/pugl'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/deps/rtosc'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/mruby'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/src/mruby-qml-parse'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/src/mruby-qml-spawn'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/src/mruby-zest'...
Cloning into '/c/Users/dmixh/Documents/Gits/zyn-fusion-build/mruby-zest-build/src/osc-bridge'...
Submodule path 'deps/mruby-complex': checked out '4f57a1ef9f968e9d5eef53667c7960a2e98c9750'
Submodule path 'deps/mruby-dir': checked out '89dceefa1250fb1ae868d4cb52498e9e24293cd1'
Submodule path 'deps/mruby-dir-glob': checked out '334c040a2e2c4c2689f8c3440168011f64d57ada'
Submodule path 'deps/mruby-errno': checked out 'b4415207ff6ea62360619c89a1cff83259dc4db0'
Submodule path 'deps/mruby-file-stat': checked out 'aa474589f065c71d9e39ab8ba976f3bea6f9aac2'
Submodule path 'deps/mruby-glew': checked out '6849202f885516b381406e799dcdb430065e19cf'
Submodule path 'deps/mruby-glfw3': checked out '0eeee012fd4bbd6544dd34f17ce2b476ad71d86b'
Submodule path 'deps/mruby-io': checked out '1c4428880b2f0f0fcd81ea2debc5f4459a7ed53c'
Submodule path 'deps/mruby-nanovg': checked out 'd7d4e1ce434131babb5fd6026201011f5b0b50ea'
Submodule path 'deps/mruby-process': checked out 'fe171fbe2a6cc3c2cf7d713641bddde71024f7c8'
Submodule path 'deps/mruby-regexp-pcre': checked out 'a961225c0953dd2bd987111f0836821573616de2'
Submodule path 'deps/mruby-set': checked out '68334311ac7386eef84f3034a256e7135a87625d'
Submodule path 'deps/mruby-sleep': checked out '263d70351a4f75a875f2a35ab9a9128d1ef5da90'
Submodule path 'deps/nanovg': checked out 'b83cf926525e7cea8d2483da2a75852b8c7b6d28'
Submodule path 'deps/pugl': checked out 'd87062625ed652df9455bd6f60ea89c53515c43a'
Submodule path 'deps/rtosc': checked out '6a65b24469068a8f334567b72a3125bd1d7fd1b1'
Submodule path 'mruby': checked out '7e229c470ae7aa2187b0fe9d3b66ac20943cd2b8'
Submodule path 'src/mruby-qml-parse': checked out '3e2c32cc55c60027e6406eca89bf1ae5301aa16b'
Submodule path 'src/mruby-qml-spawn': checked out 'ff5a0417bb37c72967e1c551c9f39c2e47a2b503'
Submodule path 'src/mruby-zest': checked out '586ef1a92b9805b204365c80f80494904959b5ae'
Submodule path 'src/osc-bridge': checked out '2816cacae0346ba363080b4a352037a06088889c'
error: patch failed: mrbgem.rake:8
error: mrbgem.rake: patch does not apply
```

**Comment by fundamental** [comment] 2020-05-14 12:29
Sounds like it's encountering the problem that the pending pull request #39 or #43 address.

**Comment by FormulaGX** [comment] 2020-05-16 19:26
Thank you for sending me these, I haven't been able to make much progress with MinGW, but ZLau92's solution may have gotten me past the zest gauntlet on Ubuntu. Now I'm at a similar point from where I had trouble with building for Linux.

```
/home/gridzydev/Documents/Gits/Zyn-Fusion-win/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp: In function ‘void zyn::preparePadSynth(std::string, zyn::PADnoteParameters*, rtosc::RtData&)’:
/home/gridzydev/Documents/Gits/Zyn-Fusion-win/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp:199:47: error: cannot convert ‘zyn::preparePadSynth(std::string, zyn::PADnoteParameters*, rtosc::RtData&)::<lambda(unsigned int, zyn::PADnoteParameters::Sample&)>’ to ‘zyn::PADnoteParameters::callback’ {aka ‘std::function<void(int, zyn::PADnoteParameters::Sample&&)>’}
  199 |                        }, []{return false;}, 1);
      |                                               ^
In file included from /home/gridzydev/Documents/Gits/Zyn-Fusion-win/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp:44:
/home/gridzydev/Documents/Gits/Zyn-Fusion-win/zyn-fusion-build/zynaddsubfx/src/Misc/../Params/PADnoteParameters.h:193:57: note:   initializing argument 1 of ‘int zyn::PADnoteParameters::sampleGenerator(zyn::PADnoteParameters::callback, std::function<bool()>, unsigned int)’
  193 |         int sampleGenerator(PADnoteParameters::callback cb,
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [src/CMakeFiles/zynaddsubfx_core.dir/build.make:540: src/CMakeFiles/zynaddsubfx_core.dir/Misc/MiddleWare.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1334: src/CMakeFiles/zynaddsubfx_core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
ERROR: 'make' failed
```

I accidentally managed to get past this point before and successfully build Linux binaries, but I cannot recall how to replicate it. I think I was at about 66% in both cases.

**Comment by deepsummersee** [comment] 2020-05-17 02:37
I'm encountering this same issue when I try to build on Windows using MinGW64. I'm somehow able to get past the Zest issues that others have mentioned but this is another roadblock I'm reaching.

**Comment by fundamental** [comment] 2020-05-17 15:47
Strange, perhaps this is some more strict behavior of a newer version of gcc or something.
I checked the commit logs and the signatures haven't been changed since 2017, but there is a difference between:
```void(int, zyn::PADnoteParameters::Sample&)``` and
 ```void(unsigned, zyn::PADnoteParameters::Sample&)```

So I guess changing the definition of PADnoteParameters::callback would suffice.
This should be something that can be verified by building zynaddsubfx/zynaddsubfx directly (or semi-directly if you're part way through a build which also builds up the dependencies).

To the best of my knowledge I don't currently have a version of gcc/clang/etc which triggers this issue though, so I cannot replicate.

**Comment by deepsummersee** [comment] 2020-05-17 18:52
OK, some things I found via some experimentation:

The backtrace issue mentioned in #33 still exists in the current repository and impedes the build process before `build-package.sh` can be executed. However, by using the workaround in #39 the backtrace problem is no longer an issue and the building process can continue to building Zyn. The process, however, abruptly stops according to the issue above but I went ahead and tried building Zest according to `build-package.sh` which takes place after the building of Zyn and is never reached normally due to the previously mentioned roadblock. After running `make windows`, the following error manifests and halts the building process:

`LD    build/w64/bin/mruby.exe`
`C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/build/w64/lib/libmruby.a(gem.o):C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: multiple definition of 'mrb_nvg_context_type'; C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/build/w64/lib/libmruby.a(nvg_context.o):nvg_context.c:(.rdata+0x3e0): first defined here`
`collect2.exe: error: ld returned 1 exit status`
`C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/build/w64/lib/libmruby.a(gem.o):C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: multiple definition of 'mrb_nvg_context_type'; C:/msys64/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/build/w64/lib/libmruby.a(nvg_context.o):nvg_context.c:(.rdata+0x3e0): first defined here`
`collect2.exe: error: ld returned 1 exit status`
`rake aborted!`
`Command failed with status (1): [gcc -L/home/bep/zyn-fusion-build-master/mr...]`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:31:in '_run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:36:in 'rescue in _run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:32:in '_run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in 'run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/rakefile:79:in 'block (4 levels) in <top (required)>'`

`Caused by:`
`Command failed with status (1): [gcc -L/home/bep/zyn-fusion-build-master/mr...]`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:33:in '_run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in 'run'`
`/home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/rakefile:79:in 'block (4 levels) in <top (required)>'`
`Tasks: TOP => default => all => /home/bep/zyn-fusion-build-master/mruby-zest-build/mruby/build/w64/bin/mruby.exe`
`(See full trace by running task with --trace)`
`make: *** [Makefile:42: windows] Error 1`

This was done in the MinGW64 shell but it doesn't seem to be a Windows exclusive thing since there seems to be some people having [a very similar issue with building Zest from the AUR.](https://github.com/mruby-zest/mruby-zest-build/issues/25#issue-618351091). So, even if the building of Zyn succeeded, the process would still halt with the building of Zest.

**Comment by FormulaGX** [comment] 2020-05-19 06:06
**Off-topic** (not sure if it'll come up again)

> Strange, perhaps this is some more strict behavior of a newer version of gcc or something.
> I checked the commit logs and the signatures haven't been changed since 2017, but there is a difference between:
> void(int, zyn::PADnoteParameters::Sample&) and
> void(unsigned, zyn::PADnoteParameters::Sample&)
> 
> So I guess changing the definition of PADnoteParameters::callback would suffice.
> This should be something that can be verified by building zynaddsubfx/zynaddsubfx directly (or semi-directly if you're part way through a build which also builds up the dependencies).
> 
> To the best of my knowledge I don't currently have a version of gcc/clang/etc which triggers this issue though, so I cannot replicate.

I tried that, but it didn't work out. Later, I changed the & operator to && in **Middleware.cpp Ln:193 Col:63**. It worked, but I just hope I didn't do anything stupid. 😅

**Comment by Nebula-Mechanica** [comment] 2020-05-19 18:41
> 
> 
> **Off-topic** (not sure if it'll come up again)
> 
> > Strange, perhaps this is some more strict behavior of a newer version of gcc or something.
> > I checked the commit logs and the signatures haven't been changed since 2017, but there is a difference between:
> > void(int, zyn::PADnoteParameters::Sample&) and
> > void(unsigned, zyn::PADnoteParameters::Sample&)
> > So I guess changing the definition of PADnoteParameters::callback would suffice.
> > This should be something that can be verified by building zynaddsubfx/zynaddsubfx directly (or semi-directly if you're part way through a build which also builds up the dependencies).
> > To the best of my knowledge I don't currently have a version of gcc/clang/etc which triggers this issue though, so I cannot replicate.
> 
> I tried that, but it didn't work out. Later, I changed the & operator to && in **Middleware.cpp Ln:193 Col:63**. It worked, but I just hope I didn't do anything stupid. 😅

That defenitely makes sense because of commit https://github.com/zynaddsubfx/zynaddsubfx/commit/651c6618255a2f1a7fceeff00d5e7bb849126469, where this change is made in many places but not in the line you changed (forgotten?).

**Comment by filip-hejsek** [comment] 2020-05-27 17:18
> That defenitely makes sense because of commit zynaddsubfx/zynaddsubfx@651c661, where this change is made in many places but not in the line you changed (forgotten?).

Indeed. The error probably wasn't noticed because it happens only on windows as it's inside `#ifdef WIN32`

**Comment by fundamental** [comment] 2020-05-28 01:05
@FormulaGX since it looks like you're the first to find the one character diff, do you want to do a PR to get your name attached to the fix? (If not I'm fine applying it now that it's clear what the issue is)

**Comment by FormulaGX** [comment] 2020-05-28 04:55
Nah, I'm a bit of a noob with git anyway. I kinda borked my workspace between then and now. Apologies. (^_^;)

**Comment by fundamental** [comment] 2020-05-30 20:27
The change is now committed.

**Closed by fundamental** 2020-05-30 20:27 UTC
